version: "3.8"
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spadb
      MYSQL_USER: camila
      MYSQL_PASSWORD: camila29

volumes:
  mysql-data:
